[versions]

kotlin = "2.2.21"
compose = "1.9.1"
agp = "8.11.2"
androidx-activityCompose = "1.11.0"
voyager_version = "1.1.0-beta03"
sdp_ssp_version = "1.0.7"
image_loader_version = "1.10.0"
media-player-version = "1.0.50"
media_kit_version = "1.0.1"

[libraries]

androidx-activityCompose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
androidx-core = { group = "androidx.core", name = "core", version = "1.17.0" }
voyager-navigator = { module = "cafe.adriel.voyager:voyager-navigator", version.ref = "voyager_version" }
voyager-transitions = { module = "cafe.adriel.voyager:voyager-transitions", version.ref = "voyager_version" }
voyager-tab = { module = "cafe.adriel.voyager:voyager-tab-navigator", version.ref = "voyager_version" }
sdp-ssp = { module = "network.chaintech:sdp-ssp-compose-multiplatform", version.ref = "sdp_ssp_version" }
image-loader = { module = "io.github.qdsfdhvh:image-loader", version.ref = "image_loader_version" }
media-player = { module = "network.chaintech:compose-multiplatform-media-player", version.ref = "media-player-version" }
media-kit = { module = "network.chaintech:media-frame-kit", version.ref = "media_kit_version" }

[plugins]

multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
mavenPublish = { id = "com.vanniktech.maven.publish", version = "0.29.0" }
